package com.example.cryptocurrency.model

import com.google.gson.annotations.SerializedName

data class CryptoDetailResponse(
    val localization: Localization?,
    val symbol: String?,
    @SerializedName("sentiment_votes_up_percentage")
    val sentimentVotesUpPercentage: Double?,
    @SerializedName("asset_platform_id")
    val assetPlatformId: String?,
    @SerializedName("public_notice")
    val publicNotice: String?,
    val description: Description?,
    @SerializedName("market_cap_rank")
    val marketCapRank: Long?,
    @SerializedName("contract_address")
    val contractAddress: String?,
    @SerializedName("sentiment_votes_down_percentage")
    val sentimentVotesDownPercentage: Double?,
    @SerializedName("liquidity_score")
    val liquidityScore: Double?,
    @SerializedName("additional_notices")
    val additionalNotices: List<Any?>?,
    @SerializedName("coingecko_score")
    val coingeckoScore: Double?,
    val id: String?,
    val categories: List<Any?>?,
    @SerializedName("genesis_date")
    val genesisDate: Any?,
    val image: com.example.cryptocurrency.model.Image?,
    @SerializedName("last_updated")
    val lastUpdated: String?,
    @SerializedName("country_origin")
    val countryOrigin: String?,
    @SerializedName("public_interest_score")
    val publicInterestScore: Double?,
    @SerializedName("status_updates")
    val statusUpdates: List<Any?>?,
    @SerializedName("community_score")
    val communityScore: Double?,
    @SerializedName("developer_score")
    val developerScore: Double?,
    @SerializedName("market_data")
    val marketData: MarketData?,
    @SerializedName("block_time_in_minutes")
    val blockTimeInMinutes: Long?,
    val name: String?,
    @SerializedName("coingecko_rank")
    val coingeckoRank: Long?,
    @SerializedName("hashing_algorithm")
    val hashingAlgorithm: String?,
)

data class MarketData(
    @SerializedName("price_change_percentage_24h")
    val priceChangePercentage24h: Double?,
    @SerializedName("price_change_24h")
    val priceChange24h: Double?,
    @SerializedName("mcap_to_tvl_ratio")
    val mcapToTvlRatio: Any?,
    @SerializedName("market_cap_rank")
    val marketCapRank: Long?,
    val roi: Any?,
    @SerializedName("atl_date")
    val atlDate: AtlDate?,
    @SerializedName("market_cap")
    val marketCap: MarketCap?,
    @SerializedName("circulating_supply")
    val circulatingSupply: Double?,
    @SerializedName("last_updated")
    val lastUpdated: String?,
    @SerializedName("total_value_locked")
    val totalValueLocked: Any?,
    @SerializedName("total_supply")
    val totalSupply: Double?,
    @SerializedName("max_supply")
    val maxSupply: Double?,
    @SerializedName("current_price")
    val currentPrice: CurrentPrice?,
    @SerializedName("price_change_percentage_1y")
    val priceChangePercentage1y: Double?,
)

data class CurrentPrice(
    val usd: Double?,
    val xdr: Double?,
    val eos: Double?,
    val sgd: Double?,
    val vef: Double?,
    val bnb: Double?,
    val eth: Double?,
    val nzd: Double?,
    val brl: Double?,
    val xag: Double?,
    val chf: Double?,
    val mxn: Double?,
    val clp: Double?,
    val bits: Double?,
    val zar: Double?,
    val vnd: Double?,
    val xau: Double?,
    val aud: Double?,
    val ils: Double?,
    val idr: Double?,
    val xrp: Double?,
    val jsonMemberTry: Double?,
    val hkd: Double?,
    val twd: Double?,
    val aed: Double?,
    val eur: Double?,
    val dkk: Double?,
    val bch: Double?,
    val cad: Double?,
    val myr: Double?,
    val dot: Double?,
    val link: Double?,
    val mmk: Double?,
    val nok: Double?,
    val btc: Double?,
    val lkr: Double?,
    val ngn: Double?,
    val czk: Double?,
    val pkr: Double?,
    val sek: Double?,
    val ltc: Double?,
    val uah: Double?,
    val bhd: Double?,
    val ars: Double?,
    val sar: Double?,
    val inr: Double?,
    val cny: Double?,
    val thb: Double?,
    val krw: Double?,
    val jpy: Double?,
    val bdt: Double?,
    val pln: Double?,
    val gbp: Double?,
    val bmd: Double?,
    val huf: Double?,
    val xlm: Double?,
    val sats: Double?,
    val kwd: Double?,
    val php: Double?,
    val yfi: Double?,
    val rub: Double? = null
)

data class MarketCap(
    val usd: Double?,
    val xdr: Double?,
    val eos: Double?,
    val sgd: Double?,
    val vef: Double?,
    val bnb: Double?,
    val eth: Double?,
    val nzd: Double?,
    val brl: Double?,
    val xag: Double?,
    val chf: Double?,
    val mxn: Double?,
    val clp: Double?,
    val bits: Double?,
    val zar: Double?,
    val vnd: Double?,
    val xau: Double?,
    val aud: Double?,
    val ils: Double?,
    val idr: Double?,
    val xrp: Double?,
    val jsonMemberTry: Double?,
    val hkd: Double?,
    val twd: Double?,
    val aed: Double?,
    val eur: Double?,
    val dkk: Double?,
    val bch: Double?,
    val cad: Double?,
    val myr: Double?,
    val dot: Double?,
    val link: Double?,
    val mmk: Double?,
    val nok: Double?,
    val btc: Double?,
    val lkr: Double?,
    val ngn: Double?,
    val czk: Double?,
    val pkr: Double?,
    val sek: Double?,
    val ltc: Double?,
    val uah: Double?,
    val bhd: Double?,
    val ars: Double?,
    val sar: Double?,
    val inr: Double?,
    val cny: Double?,
    val thb: Double?,
    val krw: Double?,
    val jpy: Double?,
    val bdt: Double?,
    val pln: Double?,
    val gbp: Double?,
    val bmd: Double?,
    val huf: Double?,
    val xlm: Double?,
    val sats: Double?,
    val kwd: Double?,
    val php: Double?,
    val yfi: Double?,
    val rub: Double?
)

data class AtlDate(
    val usd: String?,
    val xdr: String?,
    val eos: String?,
    val sgd: String?,
    val vef: String?,
    val bnb: String?,
    val eth: String?,
    val nzd: String?,
    val brl: String?,
    val xag: String?,
    val chf: String?,
    val mxn: String?,
    val clp: String?,

    val bits: String?,
    val zar: String?,
    val vnd: String?,
    val xau: String?,
    val aud: String?,
    val ils: String?,
    val idr: String?,
    val xrp: String?,
    val jsonMemberTry: String?,
    val hkd: String?,
    val twd: String?,
    val aed: String?,
    val eur: String?,
    val dkk: String?,
    val bch: String?,
    val cad: String?,
    val myr: String?,
    val dot: String?,
    val link: String?,
    val mmk: String?,
    val nok: String?,
    val btc: String?,
    val lkr: String?,
    val ngn: String?,
    val czk: String?,
    val pkr: String?,
    val sek: String?,
    val ltc: String?,
    val uah: String?,
    val bhd: String?,
    val ars: String?,
    val sar: String?,
    val inr: String?,
    val cny: String?,
    val thb: String?,
    val krw: String?,
    val jpy: String?,
    val bdt: String?,
    val pln: String?,
    val gbp: String?,
    val bmd: String?,
    val huf: String?,
    val xlm: String?,
    val sats: String?,
    val kwd: String?,
    val php: String?,
    val yfi: String?,
    val rub: String?
)

data class Localization(
    val de: String?,
    val hi: String?,
    val no: String?,
    val ru: String?,
    val fi: String?,
    val pt: String?,
    val bg: String?,
    val lt: String?,
    val hr: String?,
    val fr: String?,
    val hu: String?,
    val uk: String?,
    val sk: String?,
    val sl: String?,
    val id: String?,
    val sv: String?,
    val ko: String?,
    @SerializedName("zh-tw")
    val zhTw: String?,
    val el: String?,
    val en: String?,
    val it: String?,
    val es: String?,
    val zh: String?,
    val cs: String?,
    val ar: String?,
    val vi: String?,
    val th: String?,
    val ja: String?,
    val pl: String?,
    val da: String?,
    val he: String?,
    val nl: String?,
    val tr: String?,
)

data class Description(
    val de: String?,
    val hi: String?,
    val no: String?,
    val ru: String?,
    val fi: String?,
    val pt: String?,
    val bg: String?,
    val lt: String?,
    val hr: String?,
    val fr: String?,
    val hu: String?,
    val uk: String?,
    val sk: String?,
    val sl: String?,
    val id: String?,
    val sv: String?,
    val ko: String?,
    @SerializedName("zh-tw")
    val zhTw: String?,
    val el: String?,
    val en: String?,
    val it: String?,
    val es: String?,
    val zh: String?,
    val cs: String?,
    val ar: String?,
    val vi: String?,
    val th: String?,
    val ja: String?,
    val pl: String?,
    val ro: String?,
    val da: String?,
    val he: String?,
    val nl: String?,
    val tr: String?
)

data class Image(
    val small: String?,
    val large: String?,
    val thumb: String?,
)